name: Test
on:
  pull_request:
    branches:
    - main
    types: ["opened", "labeled", "ready_for_review", "review_request_removed"]
  pull_request_review:
    branches:
    - main

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
    - uses: antoninbas/review-manager@main
      with:
        area_ownership_file: 'AREA-OWNERS'
