name: Test
on:
  pull_request_target:
    branches:
    - main
    types: ["opened", "synchronized", "reopened", "labeled", "unlabeled", "ready_for_review", "review_request_removed"]
  pull_request_review:
    branches:
    - main

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
    - name: Check-out code
      uses: actions/checkout@v2
    - uses: antoninbas/review-manager@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        area_ownership_file: 'AREA-OWNERS'
